wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.8
    t:
      1:
      - 3
      2:
      - 3
      4: 3.7.8
      5: 0.11.0
      8:
      - 5
algo:
  desc: null
  value: sac
alpha:
  desc: null
  value: 0.2
batch_size:
  desc: null
  value: 128
buffer_capacity:
  desc: null
  value: 20000
epochs:
  desc: null
  value: 20
epsilon:
  desc: null
  value: 0.2
gamma:
  desc: null
  value: 0.993
lmbda:
  desc: null
  value: 0.7
lr_a:
  desc: null
  value: 0.0002
lr_c:
  desc: null
  value: 0.0002
tau:
  desc: null
  value: 0.995
training_batch:
  desc: null
  value: 1024
use_attention:
  desc: null
  value: false
