#!/bin/bash

export LD_LIBRARY_PATH=/home/swagat/.mujoco/mujoco200/bin${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export LD_LIBRARY_PATH=/home/swagat/.mujoco/mjpro150/bin${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MUJOCO_KEY_PATH=/home/swagat/.mujoco${MUJOCO_KEY_PATH}
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so
